
CREATE DATABASE QLBH_WPF
GO
USE QLBH_WPF
GO
CREATE TABLE Users
(
	UserName VARCHAR(255) NOT NULL UNIQUE,
	Password VARCHAR(MAX) NOT NULL,
	FullName VARCHAR(MAX),
	Email VARCHAR(255) NOT NULL,
	Phone VARCHAR(13) NOT NULL,
	Avatar NVARCHAR(MAX),
	SESSION_ID VARCHAR(10),
	CreatedAt DATETIME DEFAULT GETDATE(),
	CreatedBy VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(UserName),
	UpdatedAt DATETIME DEFAULT GETDATE(),
	UpdatedBy VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(UserName),
	CONSTRAINT PK_Users PRIMARY KEY (UserName),
)
GO
CREATE TABLE Departments
(
	DepartmentID VARCHAR(3) NOT NULL,
	DepartmentName  NVARCHAR(MAX),
	Description NVARCHAR(MAX),
	CreatedAt DATETIME DEFAULT GETDATE(),
	CreatedBy VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(UserName),
	UpdatedAt DATETIME DEFAULT GETDATE(),
	UpdatedBy VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(UserName),
)
GO
CREATE TABLE Customers
(
	CustomerID VARCHAR(10) NOT NULL,
	CustomerName NVARCHAR(MAX) NOT NULL,
	Address NVARCHAR(MAX),
	Phone VARCHAR(13),
	Email VARCHAR(255),
	CreatedAt DATETIME DEFAULT GETDATE(),
	CreatedBy VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(UserName),
	UpdatedAt DATETIME DEFAULT GETDATE(),
	UpdatedBy VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(UserName),
)
GO
CREATE TABLE Suppliers
(
	SupplierID VARCHAR(10) NOT NULL PRIMARY KEY,
	SupplierName NVARCHAR(MAX),
	Address NVARCHAR(MAX),
	Phone VARCHAR(13),
	Email VARCHAR(255),
	CreatedAt DATETIME DEFAULT GETDATE(),
	CreatedBy VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(UserName),
	UpdatedAt DATETIME DEFAULT GETDATE(),
	UpdatedBy VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(UserName),
)
GO
CREATE TABLE Unit
(
	ID int  IDENTITY(1,1) NOT NULL PRIMARY KEY,
	SupplierName NVARCHAR(MAX),
	Address NVARCHAR(MAX),
	Phone VARCHAR(13),
	Email VARCHAR(255),
	CreatedAt DATETIME DEFAULT GETDATE(),
	CreatedBy VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(UserName),
	UpdatedAt DATETIME DEFAULT GETDATE(),
	UpdatedBy VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(UserName),
)
GO
CREATE TABLE Employees
(
	ID VARCHAR(10) NOT NULL PRIMARY KEY,
	FullName NVARCHAR(MAX),
	Address NVARCHAR(MAX),
	Birthday DATE,
	Phone VARCHAR(13),
	Email VARCHAR(255),
	IDNumber VARCHAR(12) NOT NULL,
	UserName VARCHAR(255) NOT NULL,
	DepartmentID VARCHAR(3) NOT NULL,
	DateOfJobStarted DATE,
	CreatedAt DATETIME DEFAULT GETDATE(),
	CreatedBy VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(UserName),
	UpdatedAt DATETIME DEFAULT GETDATE(),
	UpdatedBy VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(UserName),
)
GO

CREATE TABLE ProductType
(
	ID int IDENTITY(1,1) NOT NULL PRIMARY KEY,
	ProductTypeName NVARCHAR(MAX),
	CreatedAt DATETIME DEFAULT GETDATE(),
	CreatedBy VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(UserName),
	UpdatedAt DATETIME DEFAULT GETDATE(),
	UpdatedBy VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(UserName),
)
GO

CREATE TABLE ProductInput
(
	ID VARCHAR(10) NOT NULL PRIMARY KEY,
	SupplierID VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES Suppliers(SupplierID),
	Payments int NOT NULL,
	TotalPrice DECIMAL(15,2),
	CreatedAt DATETIME DEFAULT GETDATE(),
	CreatedBy VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(UserName),
	UpdatedAt DATETIME DEFAULT GETDATE(),
	UpdatedBy VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(UserName),
)
GO

CREATE TABLE ProductOutput
(
	ID VARCHAR(10) NOT NULL PRIMARY KEY,
	CustomerID VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES Customers(CustomerID),
	EmployeeID VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES Employees(ID),
	DeliveryDate DATE,
	Address NVARCHAR(MAX),
	CustomerPhone VARCHAR(13),
	EmployeePhone VARCHAR(13),
	TotalPrice DECIMAL(15,2),
	Payments int NOT NULL,
	Date int,
	Month int,
	Year int,
	CreatedAt DATETIME DEFAULT GETDATE(),
	CreatedBy VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(UserName),
	UpdatedAt DATETIME DEFAULT GETDATE(),
	UpdatedBy VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(UserName),
)
GO

CREATE TABLE Brands
(
	ID int IDENTITY(1,1) NOT NULL PRIMARY KEY,
	BrandName NVARCHAR(MAX),
	CreatedAt DATETIME DEFAULT GETDATE(),
	CreatedBy VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(UserName),
	UpdatedAt DATETIME DEFAULT GETDATE(),
	UpdatedBy VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(UserName),
)

CREATE TABLE Products
(
	ProductID VARCHAR(10) NOT NULL PRIMARY KEY,
	ProductName NVARCHAR(MAX),
	BrandID int NOT NULL FOREIGN KEY REFERENCES Brands(ID),
	SupplierID VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES Suppliers(SupplierID),
	TypeID int NOT NULL FOREIGN KEY REFERENCES ProductType(ID),
	UnitID int NOT NULL FOREIGN KEY REFERENCES Unit(ID),
	BuyPrice DECIMAL(15,2),
	SellPrice DECIMAL(15,2),
	ManufactureDate DATE,
	Expiry DATE,
	Amount int,
	Code VARCHAR(MAX),
	CreatedAt DATETIME DEFAULT GETDATE(),
	CreatedBy VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(UserName),
	UpdatedAt DATETIME DEFAULT GETDATE(),
	UpdatedBy VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(UserName),
)
GO

CREATE TABLE OutputDetail
(
	ID int IDENTITY(1,1) NOT NULL PRIMARY KEY,
	OutputID VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES ProductOutput(ID),
	ProductID VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES Products(ProductID),
	Amount int,
	Discount VARCHAR(6),
	Price DECIMAL(15,2),
	Remark NVARCHAR(MAX),
	CreatedAt DATETIME DEFAULT GETDATE(),
	CreatedBy VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(UserName),
	UpdatedAt DATETIME DEFAULT GETDATE(),
	UpdatedBy VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(UserName),
)
GO

CREATE TABLE InputDetail
(
	ID int IDENTITY(1,1) NOT NULL PRIMARY KEY,
	InputID VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES ProductInput(ID),
	ProductID VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES Products(ProductID),
	Amount int,
	Discount VARCHAR(6),
	Price DECIMAL(15,2),
	WholePrice DECIMAL(15,2),
	RetailPrice DECIMAL(15,2),
	AgencyPrice DECIMAL(15,2),
	Remark NVARCHAR(MAX),
	CreatedAt DATETIME DEFAULT GETDATE(),
	CreatedBy VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(UserName),
	UpdatedAt DATETIME DEFAULT GETDATE(),
	UpdatedBy VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(UserName),
)
GO

CREATE TABLE RefundOfCustomer
(
	ID VARCHAR(10) NOT NULL PRIMARY KEY,
	PartnershipID VARCHAR(10) NOT NULL  FOREIGN KEY REFERENCES Customers(CustomerID),
	OutputID VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES ProductOutput(ID),
	TotalPrice DECIMAL(15,2),
	CreatedAt DATETIME DEFAULT GETDATE(),
	CreatedBy VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(UserName),
	UpdatedAt DATETIME DEFAULT GETDATE(),
	UpdatedBy VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(UserName),
)
GO

CREATE TABLE RefundForSupplier
(
	ID VARCHAR(10) NOT NULL PRIMARY KEY,
	PartnershipID VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES Suppliers(SupplierID),
	InputID VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES ProductInput(ID),
	TotalPrice DECIMAL(15,2),
	CreatedAt DATETIME DEFAULT GETDATE(),
	CreatedBy VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(UserName),
	UpdatedAt DATETIME DEFAULT GETDATE(),
	UpdatedBy VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(UserName),
)
GO

CREATE TABLE ROCDetail
(
	ID int IDENTITY(1,1) PRIMARY KEY,
	RefundID VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES RefundOfCustomer(ID),
	ProductID VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES Products(ProductID),
	Amount int,
	CreatedAt DATETIME DEFAULT GETDATE(),
	CreatedBy VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(UserName),
	UpdatedAt DATETIME DEFAULT GETDATE(),
	UpdatedBy VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(UserName),
)
GO

CREATE TABLE RFSDetail
(
	ID int IDENTITY(1,1) PRIMARY KEY,
	RefundID VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES RefundForSupplier(ID),
	ProductID VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES Products(ProductID),
	Amount int,
	CreatedAt DATETIME DEFAULT GETDATE(),
	CreatedBy VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(UserName),
	UpdatedAt DATETIME DEFAULT GETDATE(),
	UpdatedBy VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(UserName),
)
/*
	Level 1: Nh?n vi?n
	Level 2: Qu?n l?
	Level 3: Ch? qu?n
	Level 4: Qu?n tr? h? th?ng
*/
CREATE TABLE Authorities
(
	ID int IDENTITY(1,1) NOT NULL PRIMARY KEY,
	AuthorityName NVARCHAR(255),
	Level int,
	CreatedAt DATETIME DEFAULT GETDATE(),
	CreatedBy VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(UserName),
	UpdatedAt DATETIME DEFAULT GETDATE(),
	UpdatedBy VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(UserName),
)
GO

CREATE TABLE 
--ALTER TABLE Users
--ADD CONSTRAINT PK_Users PRIMARY KEY (UserName)
--GO
--ALTER TABLE Users
--ADD UNIQUE (UserName)
--GO
alter table Suppliers
add constraint PK_Suppliers primary key(SupplierID)
go
alter table Customers
add constraint PK_Customers primary key(CustomerID)
drop table RFSDetail
drop table ROCDetail

insert into Authorities
(
	AuthorityName,
	Level,
	CreatedBy,
	UpdatedBy
)
values(N'Qu?n l? h? th?ng', 4, 'admin', 'admin')