//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBH_WPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        private string _session_id;
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string SESSION_ID
        {
            get
            {
                return _session_id;
            }
                set
            {
                _session_id = InitSession();
            }
        }

        private string InitSession()
        {
            Random rd = new Random();
            string fullStr = "!@_\\/0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
            int len = fullStr.Length;
            string str = "";
            for(int i = 0; i < 10; i++)
            {
                int index = rd.Next(0, len - 1);
                str += fullStr[index];
            }
            return str;
        }
    }
}
